### ISSUE TITLE
New hash type for hashrekord

### ISSUE THREAD

**Issue by laurentsimon** [trailofbits/sigstore-rekor-types#22]
Hi, I'm working with Sigstore team to add a new hash type to hashedrekord.

I'd like to send a PR to add support in this repo, so that I can make use of it with sigstore-python API.

AFAICT, I'll just need to add an entry to the enum https://github.com/trailofbits/sigstore-rekor-types/blob/main/rekor_types/_internal/hashedrekord.py#L46-L49

Is my understanding correct?

**Comment by woodruffw** [comment]
> AFAICT, I'll just need to add an entry to the enum https://github.com/trailofbits/sigstore-rekor-types/blob/main/rekor_types/_internal/hashedrekord.py#L46-L49

Yes, although you shouldn't need to do anything! That whole file is code-generated from Rekor's JSON Schemas, so once the corresponding change is made to `hashedrekord` I can re-run the CI to update that file 🙂

**Comment by woodruffw** [comment]
(If you have a public link for the hashedrekord change, could you link it here? That way I can track + confirm that the CI automation works as expected 🙂)

**Comment by laurentsimon** [comment]
> > AFAICT, I'll just need to add an entry to the enum https://github.com/trailofbits/sigstore-rekor-types/blob/main/rekor_types/_internal/hashedrekord.py#L46-L49
> 
> Yes, although you shouldn't need to do anything! That whole file is code-generated from Rekor's JSON Schemas, so once the corresponding change is made to `hashedrekord` I can re-run the CI to update that file 🙂

ah! Great!

> (If you have a public link for the hashedrekord change, could you link it here? That way I can track + confirm that the CI automation works as expected 🙂)

I will. @bobcallaway will send the PR on rekor side. We'll link here when done. Thank you!

**Comment by woodruffw** [comment]
This has landed with #26 🙂
